# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  (1..2).each do |i|
    config.vm.define "multinode#{i}" do |node|
      node.vm.hostname = "multinode#{i}"
      node.vm.box = "ubuntu/xenial64"
      node.vm.network "private_network", ip: "192.168.33.1#{i}"

      # Opsional. Edit sesuai dengan nama network adapter di komputer
      # node.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 3165"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = "multinode#{i}"
        vb.gui = false
        vb.memory = "1024"
      end

      # node.vm.provision "shell", path: "bootstrap.sh", privileged: false
    end
  end
end