# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.box = "bento/ubuntu-18.04"
    master.vm.network "private_network", ip: "192.168.33.10"

    # Opsional. Edit sesuai dengan nama network adapter di komputer
    # node.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 3165"
      
    master.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.gui = false
      vb.memory = "2046"
    end

    # master.vm.provision "shell", path: "provision/bootstrap.sh", privileged: false
  end

  (1..2).each do |i|
    config.vm.define "slave#{i}" do |node|
      node.vm.hostname = "slave#{i}"
      node.vm.box = "bento/ubuntu-18.04"
      node.vm.network "private_network", ip: "192.168.33.1#{i}"

      # Opsional. Edit sesuai dengan nama network adapter di komputer
      # node.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 3165"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = "slave#{i}"
        vb.gui = false
        vb.memory = "1024"
      end

      # node.vm.provision "shell", path: "provision/bootstrap.sh", privileged: false
    end
  end
end
